name: Build Kernel

on:
  workflow_dispatch:
env: 
  CI: false
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v10
      with:
        swap-size-mb: 32768

    - name: Checkout main repository
      uses: actions/checkout@v4.1.7
      with:
        repository: ahmedmoselhi/SM-A155F_15_Opensource
        
    - name: Sync toolchains from GitLab
      run: |
        git clone --depth=1 -b A155F https://gitlab.com/ahmedmoselhi/SM-A155F_15_Opensource toolchain
        cd toolchain
        cp -r * ../
        
    - name: Sync Anykernel3
      run: |
        git clone --depth=1 --branch A15 https://github.com/ahmedmoselhi/AnyKernel3 AnyKernel3
        
    - name: Set up build environment  
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev \
                                  lftp zstd wget libfl-dev libarchive-tools
                                  
    - name: Adjust python version
      uses: MatteoH2O1999/setup-python@v5
      with:
        python-version: '2.7'                                  

    - name: Build kernel
      env: 
        CI: false
      run: |
        bash build_kernel.sh
        
    - name: Pack AnyKernel3 ZIP
      run: |
        cp -f out/arch/arm64/boot/Image.gz ./AnyKernel3/
        cd AnyKernel3/
        rm -rf .git .github README.md
        zip -r9 a155f-kernel.zip *
        
    - name: Upload AnyKernel3 ZIP
      uses: actions/upload-artifact@v4.3.4
      with:
        name: a155f-kernel.zip
        path: AnyKernel3/a155f-kernel.zip
 
  build-release:
    needs: [ build ]
    name: "Build Release"
    runs-on: "ubuntu-24.04"
    steps:
    
      - uses: actions/download-artifact@v4.3.0
        with:
          path: AnyKernel3

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: AnyKernel3/

      - name: Upload binaries to release
        uses: "diillson/auto-release@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"        
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"        
          files: |
            /home/runner/work/SM-A155F_15_Opensource/SM-A155F_15_Opensource/AnyKernel3/a155f-kernel.zip